# Generated by Django 5.1.15 on 2026-07-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urla', '0003_loanapplication_last_truv_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('system', 'System'), ('truv', 'Truv'), ('user', 'User')], default='system', max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_entries', to='urla.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
