# Generated by Django 5.1.15 on 2026-07-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urla', '0003_loanapplication_last_truv_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('verification_report', 'Verification Report'), ('ocr_paystub', 'OCR Paystub'), ('ocr_w2', 'OCR W-2'), ('invoice', 'Invoice'), ('gse_report', 'GSE Report Artifact'), ('other', 'Other')], max_length=30)),
                ('source', models.CharField(choices=[('truv_report', 'Truv Report'), ('truv_ocr', 'Truv Document Processing'), ('uploaded', 'Uploaded'), ('gse_artifact', 'Locally Synthesized GSE Artifact')], max_length=20)),
                ('truv_report_type', models.CharField(blank=True, help_text='voie, voa, income_insights, pll, assets', max_length=30)),
                ('truv_report_id', models.CharField(blank=True, max_length=64)),
                ('data', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='urla.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
