# Generated by Django 5.1.15 on 2026-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('verification_report', 'Verification Report'), ('ocr_paystub', 'OCR Paystub'), ('ocr_w2', 'OCR W-2'), ('invoice', 'Invoice'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('truv_report', 'Truv Report'), ('truv_ocr', 'Truv Document Processing'), ('uploaded', 'Uploaded'), ('sample_report', 'Truv-Published Sample Report')], max_length=20),
        ),
    ]
