# Generated by Django 5.1.15 on 2026-07-28 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_type', models.CharField(choices=[('primary', 'Primary'), ('co_borrower', 'Co-Borrower')], default='primary', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('ssn', models.CharField(blank=True, max_length=11)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('citizenship_type', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('loan_number', models.CharField(max_length=30, unique=True)),
                ('application_number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted_to_los', 'Submitted to LOS'), ('in_underwriting', 'In Underwriting')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlaFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('borrower_info', 'Section 1a — Borrower Information'), ('employment_income', 'Section 1e — Employment & Income'), ('assets', 'Section 2a — Assets'), ('liabilities', 'Section 2c — Liabilities'), ('reo', 'Section 4 — Real Estate Owned'), ('loan_property', 'Section 4 — Loan & Property'), ('declarations', 'Declarations'), ('demographics', 'Section 8 — Demographic Information')], max_length=30)),
                ('model_name', models.CharField(max_length=50)),
                ('truv_fillable', models.BooleanField(default=False)),
                ('truv_source_path', models.CharField(blank=True, help_text="Dotted path (with numeric indices for list items) into an order's employer/financial_institution entry, e.g. 'employments.0.income.pay_rate'.", max_length=200)),
                ('encompass_field_id', models.CharField(blank=True, help_text='e.g. FE0102, DD0108', max_length=10)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['section', 'field_key'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('retirement', 'Retirement'), ('other', 'Other')], default='checking', max_length=30)),
                ('financial_institution_name', models.CharField(blank=True, max_length=200)),
                ('account_number_masked', models.CharField(blank=True, max_length=30)),
                ('cash_or_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='urla.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_to_occupy_primary', models.BooleanField(null=True)),
                ('ownership_interest_last_3_years', models.BooleanField(null=True)),
                ('outstanding_judgments', models.BooleanField(null=True)),
                ('bankruptcy_last_7_years', models.BooleanField(null=True)),
                ('foreclosure_last_7_years', models.BooleanField(null=True)),
                ('party_to_lawsuit', models.BooleanField(null=True)),
                ('delinquent_federal_debt', models.BooleanField(null=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='urla.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='DemographicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(blank=True, max_length=50)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, max_length=30)),
                ('application_taken_method', models.CharField(blank=True, max_length=30)),
                ('info_provided_by_observation', models.BooleanField(null=True)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_info', to='urla.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('employer_address', models.CharField(blank=True, max_length=300)),
                ('position_title', models.CharField(blank=True, max_length=150)),
                ('is_current', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('w2', 'W-2'), ('self_employed', 'Self-Employed'), ('military', 'Military'), ('other', 'Other')], default='w2', max_length=20)),
                ('monthly_income_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_income_overtime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_income_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_income_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ownership_share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='urla.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_type', models.CharField(choices=[('revolving', 'Revolving'), ('installment', 'Installment'), ('mortgage', 'Mortgage'), ('heloc', 'HELOC'), ('other', 'Other')], default='revolving', max_length=30)),
                ('creditor_name', models.CharField(blank=True, max_length=200)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unpaid_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('to_be_paid_at_closing', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='urla.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAndProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_purpose', models.CharField(choices=[('purchase', 'Purchase'), ('refinance', 'Refinance')], default='purchase', max_length=20)),
                ('property_address', models.CharField(blank=True, max_length=300)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('occupancy_type', models.CharField(choices=[('primary', 'Primary Residence'), ('second_home', 'Second Home'), ('investment', 'Investment')], default='primary', max_length=20)),
                ('estimated_property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_property', to='urla.loanapplication')),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='urla.loanapplication'),
        ),
        migrations.CreateModel(
            name='OtherIncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_income', to='urla.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateOwned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('retained', 'Retained'), ('sold', 'Sold'), ('pending', 'Pending')], default='retained', max_length=20)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_rental_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mortgage_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_owned', to='urla.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='FieldFillState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_source', models.CharField(choices=[('unfilled', 'Not yet filled'), ('truv_auto', 'Auto-filled from Truv'), ('manual', 'Manually entered'), ('los_override', 'Corrected by underwriter')], default='unfilled', max_length=20)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('truv_order_id', models.CharField(blank=True, max_length=64)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urla.borrower')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_fill_states', to='urla.loanapplication')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='urla.urlafielddefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('loan_application', 'field_definition', 'borrower'), name='urla_one_fill_state_per_field_per_borrower')],
            },
        ),
    ]
