# Generated by Django 5.1.15 on 2026-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urla', '0002_seed_field_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='last_truv_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
