# Generated by Django 5.1.15 on 2026-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urla', '0005_correct_asset_field_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='account_number_masked',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='liability',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
