# Generated by Django 5.1.15 on 2026-07-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urla', '0007_seed_liability_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanandproperty',
            name='loan_program',
            field=models.CharField(blank=True, choices=[('conventional', 'Conventional'), ('fha', 'FHA'), ('va', 'VA'), ('usda', 'USDA'), ('jumbo', 'Jumbo'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='loanandproperty',
            name='loan_term_months',
            field=models.PositiveIntegerField(blank=True, default=360, null=True),
        ),
        migrations.AddField(
            model_name='loanandproperty',
            name='note_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
