# Generated by Django 5.1.15 on 2026-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urla', '0009_correct_employer_name_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanandproperty',
            name='funding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanandproperty',
            name='loan_processor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loanandproperty',
            name='loan_processor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='loanandproperty',
            name='originator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loanandproperty',
            name='originator_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
