# Generated by Django 5.1.15 on 2026-07-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urla', '0002_seed_field_definitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_method', models.CharField(choices=[('embedded_order', 'Embedded Orders'), ('hosted_order', 'Hosted Orders'), ('bridge_token', 'Bridge Token'), ('document_upload', 'Document Processing')], max_length=20)),
                ('products', models.JSONField(default=list)),
                ('data_sources', models.JSONField(default=list)),
                ('template_id', models.CharField(blank=True, max_length=100)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('company_mapping_id', models.CharField(blank=True, max_length=100)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('truv_order_id', models.CharField(blank=True, max_length=64)),
                ('truv_user_id', models.CharField(blank=True, max_length=64)),
                ('bridge_token', models.CharField(blank=True, max_length=500)),
                ('share_url', models.URLField(blank=True)),
                ('document_collection_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='created', max_length=30)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='urla.loanapplication')),
            ],
        ),
    ]
