# Generated by Django 5.1.15 on 2026-07-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepVerificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(choices=[('employment', 'Employment & Income'), ('assets', 'Assets'), ('combined', 'Combined Income & Assets')], max_length=20, unique=True)),
                ('integration_method', models.CharField(choices=[('embedded_order', 'Embedded Orders'), ('hosted_order', 'Hosted Orders'), ('bridge_token', 'Bridge Token'), ('document_upload', 'Document Processing')], default='embedded_order', max_length=20)),
                ('products', models.JSONField(default=list)),
                ('data_sources', models.JSONField(default=list)),
                ('template_id', models.CharField(blank=True, max_length=100)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('company_mapping_id', models.CharField(blank=True, max_length=100)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
