# Generated by Django 5.1.15 on 2026-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_stepverificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepverificationconfig',
            name='fetch_liabilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='fetch_liabilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stepverificationconfig',
            name='step_key',
            field=models.CharField(choices=[('employment', 'Employment & Income'), ('assets', 'Assets'), ('liabilities', 'Liabilities'), ('combined', 'Combined Income & Assets')], max_length=20, unique=True),
        ),
    ]
