# Generated by Django 5.1.15 on 2026-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_stepverificationconfig_fetch_liabilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='document_collection_id',
        ),
        migrations.AlterField(
            model_name='stepverificationconfig',
            name='integration_method',
            field=models.CharField(choices=[('embedded_order', 'Embedded Orders'), ('hosted_order', 'Hosted Orders'), ('bridge_token', 'Bridge Token')], default='embedded_order', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='integration_method',
            field=models.CharField(choices=[('embedded_order', 'Embedded Orders'), ('hosted_order', 'Hosted Orders'), ('bridge_token', 'Bridge Token')], max_length=20),
        ),
    ]
