# Generated by Django 5.1.15 on 2026-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truv_user_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('duration_ms', models.FloatField(null=True)),
                ('environment', models.CharField(blank=True, choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truv_user_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('truv_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('matched_environment', models.CharField(blank=True, max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TruvCredentialSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20)),
                ('client_id', models.CharField(max_length=200)),
                ('encrypted_secret', models.BinaryField()),
                ('base_url', models.URLField(help_text='e.g. https://prod.truv.com/v1/ or your sandbox host')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='truv_integration_only_one_active_credential_set')],
            },
        ),
    ]
