# Generated by Django 5.1.15 on 2026-07-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truv_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truvcredentialset',
            name='base_url',
            field=models.URLField(blank=True, default='https://prod.truv.com/v1/', help_text='Same for sandbox and production — only change this for a custom/mTLS endpoint.'),
        ),
    ]
