# Generated by Django 5.1.15 on 2026-07-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truv_integration', '0002_alter_truvcredentialset_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AimCheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.CharField(choices=[('truv_document_upload', 'Truv Document Processing'), ('aim_check_ocr', 'AIM Check via OCR')], default='truv_document_upload', max_length=30)),
                ('ocr_source', models.CharField(choices=[('sample_report', 'Sample Report'), ('encompass_edc', 'Encompass EDC (ASO)')], default='sample_report', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
