# Generated by Django 5.1.15 on 2026-07-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urla', '0008_loanandproperty_loan_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderwritingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('decided_by', models.CharField(blank=True, max_length=150)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('approved_summary', models.JSONField(blank=True, null=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='underwriting_decision', to='urla.loanapplication')),
            ],
        ),
    ]
