# Generated by Django 5.1.15 on 2026-07-29 16:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwriting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underwritingdecision',
            name='approved_summary',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
