# Generated by Django 5.1.15 on 2026-07-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urla', '0003_loanapplication_last_truv_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truv_order_id', models.CharField(max_length=64)),
                ('raw_order_response', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_snapshots', to='urla.loanapplication')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
